### ISSUE TITLE
Fix to rankfunction

### ISSUE THREAD

**Issue by ravi-annaswamy** [pcrespov/programming-collective-intelligence-segaran#2]
@pcrespov 
Thanks for creating this repo for this excellent book's code.
I changed the sort() call in this function and it works.

def getrankfunction(dataset):
    def rankfunction(population):
        scores = [(scorefunction(t, dataset), t) for t in population]
        scores=sorted(scores, key=lambda k:k[0])
        return scores
    return rankfunction

Also in your test notebook, you are having error because you have .display() unnecessary please fix the line to:
muttree = mutate(random1, 2)

Thanks
Ravi

**Comment by pcrespov** [comment]
I appreciate the input @ravi-annaswamy, I added your changes.
